// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyqekjwwhxalqwswqqax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cWVrand3aHhhbHF3c3dxcWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTIzMTIsImV4cCI6MjA2ODY2ODMxMn0.PqMmScjA_jtyW1qMrtOM4sDeYfegMwLFQTXGG1tpI0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});